### ISSUE TITLE
Literal strings bugs.

### ISSUE THREAD

**Issue by SimonWoodburyForget** [avakar/pytoml#12] opened 2015-11-29 21:35 UTC
I am using python 3.5.

Parsing with `pytoml.loads()`

This toml:

    [table]
    key = 'val\nue'

Gives out this error

    Traceback (most recent call last):
      File "<stdin>", line 4, in <module>
      File "/home/simon/venv/3.5/lib/python3.5/site-packages/pytoml/parser.py", line 23, in loads
        ast = _p_toml(src)
      File "/home/simon/venv/3.5/lib/python3.5/site-packages/pytoml/parser.py", line 344, in _p_toml
        s.expect_eof()
      File "/home/simon/venv/3.5/lib/python3.5/site-packages/pytoml/parser.py", line 124, in expect_eof
        return self._expect(self.consume_eof())
      File "/home/simon/venv/3.5/lib/python3.5/site-packages/pytoml/parser.py", line 164, in _expect
        raise TomlError('msg', self._pos[0], self._pos[1], self._filename)
    pytoml.core.TomlError: <string>(3, 1): msg

That toml:

    [table]
    key = 'val\ue'

Gives out this error:

    SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 19-21: truncated \uXXXX escape

This toml:

    [table]
    key = '''value\n'''

Gives out:

    {'table': {'key': 'value\n'}}

But should give out (*by v0.4.0 specs*):

    {'table': {'key': 'value\\n'}}

**Comment by avakar** [comment] 2015-12-01 08:27
Hi, thanks for the report. I've updated the [test suite][1] and added Python 3.5 to the test environment set, but I cannot reproduce these issues. Are you sure you have the latest version installed (currently 0.1.7)? You can upgrade the package with `pip install -U pytoml`.

  [1]: https://github.com/avakar/toml-test/commit/0b2ed3296b80c1876fa43842cdf4001655b6c6bf

**Comment by SimonWoodburyForget** [comment] 2015-12-01 10:34
*Installed it less then a day ago so that did nothing* but pip freeze says it's 0.1.7

Your commit shows `"val\ue"` but it should be `'val\ue'`, doubles and single quotes in toml are different strings, string literals and strings. String literals are like `r` raw strings in python, they escape everything for you. So i figure you'd be handling them differently.

Python gives out a syntax error when `\u` is an invalid Unicode character, but  `r"\u"` wont because it escapes it and pops out `"\\u"`. This is what the second error is about. The last error shows consistency over not escaping. The first error i seriously have no clue.

**Comment by avakar** [comment] 2015-12-01 10:41
Look a few lines below ([here][1]), the test includes single-quoted versions as well and the `\u` case.

But I think I figured it out :8ball: You're doing this

    pytoml.loads("key = 'val\nue'")

instead of this.

    pytoml.loads(r"key = 'val\nue'")

Aren't you?

  [1]: https://github.com/avakar/toml-test/commit/0b2ed3296b80c1876fa43842cdf4001655b6c6bf#diff-b0799ee199c7aa1273d7db2b68b2eeccR5

**Comment by SimonWoodburyForget** [comment] 2015-12-01 11:28
Yeah the first.... which thinking about means the second is not a bug, definitely caused by creating the string.. that one passed over my head.

**Comment by avakar** [comment] 2015-12-01 18:15
No, the first one is invalid TOML, you can't have newlines in a non-multiline string:

    key = 'val
    ue' # This isn't valid TOML

Anyway, since we found the problem, I'm closing the issue.

**Closed by avakar** 2015-12-01 18:15 UTC
